title: G—O
baseurl: /moe
description: |
  Георгий Ожегов (G—O) излагает свои мысли. Изучает что-то новое. Делится опытом.
  И пишет интересные посты о книжках, компиляторах, английском и многом другом.
permalink: pretty
collections:
  books:
    output: true
    permalink: /:collection/:name
  thoughts:
    output: true
    permalink: /:collection/:name
